* Part 1: Commodities and Money
** Commodities
*** Two Factors of a Commodity
   A commodity is composed as a two-fold of social use-value and
   exchange value.  The value of a use-value is given by the average
   socially necessary labour-time imbued into its production.

   Greater labour power results in less labour time, therefore less
   value.

   A thing can be a use-value without having value, if the thing has
   natural utility, like air or soil (and thus no labour imbued into
   it).

   Commodities have social utility, therefore a thing created to
   satisfy the want of own person (which doesn't reflect a general
   social utility) isn't a commodity, i.e. it wasn't produced for the
   use of others. Thus things produced to immediately satisfy your own
   needs, are often not commodities, as they aren't social use-values.
   
   Labour can also be useless, thus creating no value. For example,
   mudpies aren't social use-values, thus the labour contained in
   making them is useless, and doesn't produce any value.
   
*** Two-fold Character of Labour in Commodities
   Labour holds a two-fold composition, just like commodities.

   The value of a commoditiy is measured in relation to other
   commodities, at exchange. Ex. the value of a coat, can be
   represented in an amount of linen, because we exchange coats for
   linen (or linen for coats). We don't exchange coats for coats. This
   entails that the value of use-values can be represented in terms of
   qualitively different use-values consisting of qualitively
   different labour.

   Societies, whether or not they have a commodity form, have a
   division of labour. Someone produces bread, someone else produces
   houses, beds or clothing. 

   Just as the quantum of the commodity accumulation is 1 unit of
   commodity, there is a similar quantum to be found in the total
   amount of labour present in a society.

   A larger quantity of use-values is a larger quantity of material wealth.

   Even as productive power varies, labour yields the same amount of
   total value, across the same time periods. However, as productive
   power increases, this total value may manifest itself in a larger
   quantity of use-values, that each represent a less amount of value,
   than they did before the increase in productiveness. Ex. Without a
   machine, a worker can in 1 hour produce 1 hamburger. This means
   that 1 hamburger is effectively worth 1 hour of labour. The worker
   is now given a new machine, that can produce 100 hamburgers in one
   hour of labour. The labour still produces 1 hour of labour (the
   value), but it is represented in terms of a 100 hamburgers each
   worth 0.01 times the amount of value of 1 hamburger before the
   machine was introduced.

*** Forms of value
**** The Relative Form of Value
    Keep in mind that the relative form of value manifests at exchange
    i.e. exchange-value.

    The simplest relation of value is that of between two
    commodities. This is represented as ~x commodity A = y commodity B~,
    where each side of the equation represents the value of either
    commodity.

    Commodities are said to assume a relative form of expressed value,
    if its value is expressed in a quantity of another commodity. As
    aforementioned, its impossible to express the value of a
    commodity, in terms of the same commodity. ~1 commodity A = 1
    commodity A~, and from this, we cannot infer value.

    (2.a) is difficult to understand, mainly because it attempts to
    demonstrate how the relative value equations infer value of a
    commodity, and how equating materially different commodities to
    infer value is possible. We should draw from this that, value, is
    a medium for which we can relate all commodities to eachother.

    (2.a) further attempts to show that, value is essentially the
    accumulation of useful labour in a thing, and again, what exactly
    the relative form of value is.

    (2.b) presents a few interesting examples. One of these examples
    (case II), shows that the relative value equations may change
    depending on if the value in each related commodity changes. If 20
    yards of linen = 0.5 coat, and the productive power for linens is
    doubled, then the relative value of linens will now be expressed
    as ~10 yards of linen = 0.5 coat~, or ~20 yards of linen = 0.25~ coat.
    
    Another example (case III) in (2.b) shows that, given a proportional
    rise in productiveness for e.g. both linen and coats (formerly
    expressed as ~10 yards of linen = 0.5 coat~, their relative value
    equation remains constant. Each of their respective value is
    decreasing with the increase in productiveness, but still the
    equation holds that ~10 yards of linen = 0.5 coat~. However, we can
    immediately see that their value has changed, if we relate either
    commodity (linen or coat) to a third commodity with an unchanging
    productiveness.

**** The Equivalent Form of Value
**** The Elementary Form of Value as a Whole
    
    
    


*** Fetishism of Commodities and the Secret Thereof
